### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by williammarsh** [idamoltke/LocalNgsRelate#1]
Hi,

I have recently downloaded your software package, and have got it successfully running using the example data files. However, when I use my own data, I am presented with a segmentation fault. I have troubleshooted this problem to no end, and have had no luck so far. Both my freq and beagle.gz file are both of the same format seen in the example files.

Here is the command line output I receive: 

`	-> You are using LocalNgsRelate version 0.999 (build time: Nov 11 2021:12:39:13)
	-> Command running is:
	   localngsrelate -f Raw.pathlist.attempt3_reich_snp.freq -gbeagle Raw.pathlist.attempt3_reich_snp -n 15 
	   
	->NB. Since no output prefix was provided Raw.pathlist.attempt3_reich_snp will be used as prefix for all output

	-> Frequency file 'Raw.pathlist.attempt3_reich_snp.freq' successfully parsed.
	   It contained frequencies from 1150312 sites
	-> Beagle file 'Raw.pathlist.attempt3_reich_snp.beagle.gz' successfully parsed.
	   It contained data from  15 individuals at 1150312 sites.
	-> Data divided into 22 chromosomes.
Segmentation fault
`
Any help would be much appreciated. I have used this data in NGSrelate previously, prepared by ANGSD in a similar manner to what is required here. Here is my ANGSD command for beagle file creation:

`angsd -b ${NAME} -GL 1 -doGlf 2 -doMajorMinor 3 -doMaf 1 -sites {SITES} -rf chr -out ${NAME}_snp -minMapQ 30 -minQ 20 -P 4`

Additionally, I believe the example ANGSD beagle creation command provided in your manual is lacking -doGlf 2, which creates a beagle.gz file.

Best,

William

**Comment by idamoltke** [comment]
Hi William. Sorry you are encountering problems. I'll try to have a look at it asap. However, I would probably need your data (or a small subset) in order to do this. Otherwise it will be hard for me to recreate the problem and fix it, since I am not getting this error with any of the data I have tried applying the program to so far. If you are willing to share it then you can send it to idamoltke at gmail dot com along with the exact commands you used to run the analyses. Thanks, Ida

**Comment by williammarsh** [comment]
Hi Ida, 

Thanks very much for this.

I can share the data I am using with pleasure. Please email me on w.marsh(at)nhm.ac.uk to confirm details.

Best,

William

**Comment by pierrespc** [comment]
Hi,

I am following up to this problem. I can run LocalNGSrelate for many datasets. However, for one subset of sites I get the segmentation fault. I can't understand why. I checked that the beagle file is correctly made and that the marker column in it is correctly formed (chr<CHR>_<POS> and sorted by chr and pos). What puzzles me most is that I can run it using 5Millions SNPs but then when I use only the Transversions out of this list, I get this error.

Below you have the fulllog.

Thanks!

```
 more Output/1_btwPairs/LocalRelate/LocalNGSrelate.AR0001.AR0004.Thin40.fullog 

	-> You are using LocalNgsRelate version 0.999 (build time: Aug 22 2022:15:46:37)
	-> Command running is:
	   /pasteur/zeus/projets/p02/Hotpaleo/pierre/Scripts/Tools/LocalNgsRelate/localngsrelate -f /pasteur/zeus/projets/p02/Hotpaleo/pierre/Projects/2022-09-19_Analyses_5Seq_2screen_merged/Kinship/LocalNGSrelate_SG.TVs/Output/1_btwPairs//Beagle/LocalNGSrelate.Thin40.freq -gbeagle /pasteur/zeus/projets/p02/Hotpaleo/pierre/Projects/2022-09-19_Analyses_5Seq_2scre
en_merged/Kinship/LocalNGSrelate_SG.TVs/Output/1_btwPairs//Beagle/LocalNGSrelate.Thin40 -n 88 
	   -a 0 -b 1 -l 0.01 
	   -O /pasteur/zeus/projets/p02/Hotpaleo/pierre/Projects/2022-09-19_Analyses_5Seq_2screen_merged/Kinship/LocalNGSrelate_SG.TVs/Output/1_btwPairs//LocalRelate/LocalNGSrelate.Thin40.AR0001.AR0004 
	-> Frequency file '/pasteur/zeus/projets/p02/Hotpaleo/pierre/Projects/2022-09-19_Analyses_5Seq_2screen_merged/Kinship/LocalNGSrelate_SG.TVs/Output/1_btwPairs//Beagle/LocalNGSrelate.Thin40.freq' successfully parsed.
	   It contained frequencies from 63289 sites
	-> Beagle file '/pasteur/zeus/projets/p02/Hotpaleo/pierre/Projects/2022-09-19_Analyses_5Seq_2screen_merged/Kinship/LocalNGSrelate_SG.TVs/Output/1_btwPairs//Beagle/LocalNGSrelate.Thin40.beagle.gz' successfully parsed.
	   It contained data from  88 individuals at 63289 sites.
	-> Data divided into 22 chromosomes.
/var/spool/slurmd/job39824722/slurm_script: line 4: 3311064 Segmentation fault      /pasteur/zeus/projets/p02/Hotpaleo/pierre/Scripts/Tools/LocalNgsRelate/localngsrelate -f /pasteur/zeus/projets/p02/Hotpaleo/pierre/Projects/2022-09-19_Analyses_5Seq_2screen_merged/Kinship/LocalNGSrelate_SG.TVs/Output/1_btwPairs//Beagle/LocalNGSrelate.Thin40.freq -gbeagle /pasteur
/zeus/projets/p02/Hotpaleo/pierre/Projects/2022-09-19_Analyses_5Seq_2screen_merged/Kinship/LocalNGSrelate_SG.TVs/Output/1_btwPairs//Beagle/LocalNGSrelate.Thin40 -n 88 -a 0 -b 1 -l 0.01 -O /pasteur/zeus/projets/p02/Hotpaleo/pierre/Projects/2022-09-19_Analyses_5Seq_2screen_merged/Kinship/LocalNGSrelate_SG.TVs/Output/1_btwPairs//LocalRelate/LocalNGSrelate.Thin40.AR
0001.AR0004
```

**Comment by idamoltke** [comment]
Hi

It definitely sounds odd that you can run it on the full data but not a subset. If you don't mind sharing your data and the exact command your ran that gave you the segmentation fault then I can try to run it on my system and see if I can figure out why you are getting the error.

All the best,
Ida

**Comment by pierrespc** [comment]
Hi,

you should receive an email  with a link to download the data.
Please let me know when you downloaded it.
The command is 

```
/pasteur/zeus/projets/p02/Hotpaleo/pierre/Scripts/Tools/LocalNgsRelate/localngsrelate \
     -f LocalNGSrelate.Thin20.freq \
     -gbeagle LocalNGSrelate.Thin20 \
     -n 88 -a 0 -b 1 -l 0.01 \
     -O TEST

```
  Note that the Seg Fault appears with any combination of individuals (that is a {0..87} and b {0..87}).
  Best

**Comment by idamoltke** [comment]
Thanks. That was very helpful. I think I solved the issue, which was a small bug in the maf filtering of the very first site. Can I get you to download and try out the updates version of the program from GitHub? The command you provided now works with that version on my server, so hopefully it works on yours as well. 

All the best,
Ida

**Comment by pierrespc** [comment]
It is working!
Thanks for having handled the isssue so quickly. Much appreciated.
Best.
