### ISSUE TITLE
Problem parsing beagle file

### ISSUE THREAD

**Issue by tristanpwdennis** [idamoltke/LocalNgsRelate#2]
Hi,
I am attempting to run LocalNgsRelate on my data and I am running into a problem. Here is my command:

```~/packages/LocalNgsRelate/src/cpp/localngsrelate -f example.freq -gbeagle example -n 314 -a 1 -b 0```

and I get the following output:

```

	-> You are using LocalNgsRelate version 0.999 (build time: Jan 26 2022:17:07:39)
	-> Command running is:
	   /export/home2/tdd3v/packages/LocalNgsRelate/src/cpp/localngsrelate -f example.freq -gbeagle example -n 314 
	   -a 1 -b 0 
	->NB. Since no output prefix was provided example will be used as prefix for all output

	-> Frequency file 'example.freq' successfully parsed.
	   It contained frequencies from 100 sites

	##Problem parsing beagle file: ncols=632 will exit
```

I've taken a look at the data, counted the columns, and it appears to add up (e..g the number of individuals is ok...I think! Probably I am missing something obvious, so any assistance would be very welcome! I have attached some example data that will hopefully help you replicate if you need to.

Thank you for the software and assistance!

tristan
[example_data_forlocalngsrelate.tar.gz](https://github.com/idamoltke/LocalNgsRelate/files/7944173/example_data_forlocalngsrelate.tar.gz)

**Comment by populationgenetics** [comment]
Hi Tristan. 

For some reason I cannot open your attached data.  So there may be an issue with the files being corrupted somehow.  However, if this is not the case then I am noticing that according to the output you have data from 314 individuals but only 632 columns in your beagle file. This is problematic because in a beagle file there are three columns with info about the markers followed by 3 columns per individual. So there should be more than 632 columns in your beagle file if there are indeed data from 314 individuals. Can I get you to tell me how many columns and lines the beagle file contains? And how many lines the freq file contains? Or perhaps send me the files without tar.gz-ing them?

Best,
Ida

**Comment by tristanpwdennis** [comment]
Hi Ida,
Thank you for your speedy reply!
I have counted the number of columns in the beagle file and it appears correct - there are 945 columns, which corresponds to 314 individuals + the 3 info fields. The freq and beagle contain 100 sites (a subsample). I have attached the files in question as a zipped folder - let me know if you have any trouble opening them again and I could email them to you?

Also, I notice that if I extract the first two individuals of data (so the first 9 rows), LocalNGSRelate appears to run fine. The BEAGLE file was generated with ANGSD 0.922.


Thanks again
Tristan

[example_data_forlocalngsrelate.zip](https://github.com/idamoltke/LocalNgsRelate/files/7959292/example_data_forlocalngsrelate.zip)

**Comment by idamoltke** [comment]
Hi Tristan. 

Apologies for the slow reply. My little 11 month old daughter and I have been have been sick the past week. However, I finally managed to take a quick look and found two things that I think could lead to trouble - one on my end and one on your end. The one on my end should be easy to fix. I have tried to do so, so please try to redownload the new version of the program and rerun the analysis. The one on your end is that I think your example file contains frequency info for 100 sites but your beagle file only contains data for 99 sites (it has 100 lines but the first one is a header). After fixing both issues the program runs without any issues on your example data on my computer. I hope it does on yours as well? 

All the best,
Ida

**Comment by idamoltke** [comment]
ps. Right now the program assumes that your marker names consists of a chr name/number and underscore and the position. So e.g. chr1_10384. If this is not the format you are using then that might get you into trouble as well.

**Comment by tristanpwdennis** [comment]
Hi Ida
I hope you and your little one have recovered ok, thanks for getting back to me. I pulled the updated version and fixed my freq file and that's working ok now :)
Thanks for all your help!
Tristan
